// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package project_invite

import (
	"wktline-server/api/project_invite"
)

type ControllerV1 struct{}

func NewV1() project_invite.IProjectInviteV1 {
	return &ControllerV1{}
}
