// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalMessageDao is internal type for wrapping internal DAO implements.
type internalMessageDao = *internal.MessageDao

// messageDao is the data access object for table message.
// You can define custom methods on it to extend its functionality as you wish.
type messageDao struct {
	internalMessageDao
}

var (
	// Message is globally public accessible object for table message operations.
	Message = messageDao{
		internal.NewMessageDao(),
	}
)

// Fill with you ideas below.
