// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalProjectDao is internal type for wrapping internal DAO implements.
type internalProjectDao = *internal.ProjectDao

// projectDao is the data access object for table model_project.
// You can define custom methods on it to extend its functionality as you wish.
type projectDao struct {
	internalProjectDao
}

var (
	// Project is globally public accessible object for table model_project operations.
	Project = projectDao{
		internal.NewProjectDao(),
	}
)

// Fill with you ideas below.
