// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalProjectUserDao is internal type for wrapping internal DAO implements.
type internalProjectUserDao = *internal.ProjectUserDao

// projectUserDao is the data access object for table project_user.
// You can define custom methods on it to extend its functionality as you wish.
type projectUserDao struct {
	internalProjectUserDao
}

var (
	// ProjectUser is globally public accessible object for table project_user operations.
	ProjectUser = projectUserDao{
		internal.NewProjectUserDao(),
	}
)

// Fill with you ideas below.
