// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalProjectInviteDao is internal type for wrapping internal DAO implements.
type internalProjectInviteDao = *internal.ProjectInviteDao

// projectInviteDao is the data access object for table project_invite.
// You can define custom methods on it to extend its functionality as you wish.
type projectInviteDao struct {
	internalProjectInviteDao
}

var (
	// ProjectInvite is globally public accessible object for table project_invite operations.
	ProjectInvite = projectInviteDao{
		internal.NewProjectInviteDao(),
	}
)

// Fill with you ideas below.
