// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalResourceDao is internal type for wrapping internal DAO implements.
type internalResourceDao = *internal.ResourceDao

// resourceDao is the data access object for table task_attachment.
// You can define custom methods on it to extendApi its functionality as you wish.
type resourceDao struct {
	internalResourceDao
}

var (
	// Resource is globally public accessible object for table task_attachment operations.
	Resource = resourceDao{
		internal.NewResourceDao(),
	}
)

// Fill with you ideas below.
