// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalTaskPriorityDao is internal type for wrapping internal DAO implements.
type internalTaskPriorityDao = *internal.TaskPriorityDao

// taskPriorityDao is the data access object for table task_priority.
// You can define custom methods on it to extend its functionality as you wish.
type taskPriorityDao struct {
	internalTaskPriorityDao
}

var (
	// TaskPriority is globally public accessible object for table task_priority operations.
	TaskPriority = taskPriorityDao{
		internal.NewTaskPriorityDao(),
	}
)

// Fill with you ideas below.
