// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalTaskTypeDao is internal type for wrapping internal DAO implements.
type internalTaskTypeDao = *internal.TaskTypeDao

// taskTypeDao is the data access object for table task_type.
// You can define custom methods on it to extend its functionality as you wish.
type taskTypeDao struct {
	internalTaskTypeDao
}

var (
	// TaskType is globally public accessible object for table task_type operations.
	TaskType = taskTypeDao{
		internal.NewTaskTypeDao(),
	}
)

// Fill with you ideas below.
