// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalTaskLaborHourDao is internal type for wrapping internal DAO implements.
type internalTaskLaborHourDao = *internal.TaskLaborHourDao

// taskLaborHourDao is the data access object for table task_labor_hour.
// You can define custom methods on it to extend its functionality as you wish.
type taskLaborHourDao struct {
	internalTaskLaborHourDao
}

var (
	// TaskLaborHour is globally public accessible object for table task_labor_hour operations.
	TaskLaborHour = taskLaborHourDao{
		internal.NewTaskLaborHourDao(),
	}
)

// Fill with you ideas below.
