// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalTaskOperationLogDao is internal type for wrapping internal DAO implements.
type internalTaskOperationLogDao = *internal.TaskOperationLogDao

// taskOperationLogDao is the data access object for table task_operation_log.
// You can define custom methods on it to extend its functionality as you wish.
type taskOperationLogDao struct {
	internalTaskOperationLogDao
}

var (
	// TaskOperationLog is globally public accessible object for table task_operation_log operations.
	TaskOperationLog = taskOperationLogDao{
		internal.NewTaskOperationLogDao(),
	}
)

// Fill with you ideas below.
