// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalTaskGroupDao is internal type for wrapping internal DAO implements.
type internalTaskGroupDao = *internal.TaskGroupDao

// taskGroupDao is the data access object for table task_group.
// You can define custom methods on it to extend its functionality as you wish.
type taskGroupDao struct {
	internalTaskGroupDao
}

var (
	// TaskGroup is globally public accessible object for table task_group operations.
	TaskGroup = taskGroupDao{
		internal.NewTaskGroupDao(),
	}
)

// Fill with you ideas below.
