// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalTestCaseDao is internal type for wrapping internal DAO implements.
type internalTestCaseDao = *internal.TestCaseDao

// testCaseDao is the data access object for table test_case.
// You can define custom methods on it to extend its functionality as you wish.
type testCaseDao struct {
	internalTestCaseDao
}

var (
	// TestCase is globally public accessible object for table test_case operations.
	TestCase = testCaseDao{
		internal.NewTestCaseDao(),
	}
)

// Fill with you ideas below.
