// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wktline-server/internal/dao/internal"
)

// internalUserWorkPanelDao is internal type for wrapping internal DAO implements.
type internalUserWorkPanelDao = *internal.UserWorkPanelDao

// userWorkPanelDao is the data access object for table user_work_panel.
// You can define custom methods on it to extend its functionality as you wish.
type userWorkPanelDao struct {
	internalUserWorkPanelDao
}

var (
	// UserWorkPanel is globally public accessible object for table user_work_panel operations.
	UserWorkPanel = userWorkPanelDao{
		internal.NewUserWorkPanelDao(),
	}
)

// Fill with you ideas below.
