// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package test_case

import (
	"wktline-server/api/test_case"
)

type ControllerV1 struct{}

func NewV1() test_case.ITestCaseV1 {
	return &ControllerV1{}
}
